import { Bid, AwardData, CompetitorData, User, SystemLog, DashboardStats } from '@/types';

export const mockBids: Bid[] = [
  {
    id: '1',
    noticeId: 'SPE300-26-R-0012',
    title: 'USFK Base Operations Support Services - Camp Humphreys',
    type: 'Solicitation',
    status: 'active',
    postedDate: '2026-03-18',
    responseDeadline: '2026-04-15',
    agency: 'DEPT OF DEFENSE',
    office: 'DLA TROOP SUPPORT',
    location: 'Pyeongtaek, South Korea',
    naicsCode: '561210',
    naicsDescription: 'Facilities Support Services',
    setAside: 'Total Small Business Set-Aside',
    estimatedValue: 45000000,
    description: 'The Defense Logistics Agency seeks qualified contractors to provide comprehensive base operations support services at Camp Humphreys, including facility maintenance, grounds keeping, janitorial services, and related support activities for United States Forces Korea personnel.',
    contactName: 'James Miller',
    contactEmail: 'james.miller@dla.mil',
    contactPhone: '(215) 737-4000',
    solicitationNumber: 'SPE300-26-R-0012',
    placeOfPerformance: { city: 'Pyeongtaek', state: 'Gyeonggi-do', country: 'South Korea' },
    isUsfk: true,
    keywords: ['USFK', 'Camp Humphreys', 'base operations', 'facilities'],
    saved: true,
  },
  {
    id: '2',
    noticeId: 'W912CN-26-Q-0043',
    title: 'Construction of Vehicle Maintenance Facility - Osan Air Base',
    type: 'Solicitation',
    status: 'active',
    postedDate: '2026-03-15',
    responseDeadline: '2026-04-01',
    agency: 'DEPT OF DEFENSE',
    office: 'US ARMY CORPS OF ENGINEERS',
    location: 'Osan, South Korea',
    naicsCode: '236220',
    naicsDescription: 'Commercial and Institutional Building Construction',
    estimatedValue: 12000000,
    description: 'Construction of a new vehicle maintenance facility at Osan Air Base to support 7th Air Force operations. The project includes a main maintenance bay, administrative offices, parts storage, and associated utilities.',
    contactName: 'Sarah Johnson',
    contactEmail: 's.johnson@usace.army.mil',
    contactPhone: '(808) 835-4000',
    solicitationNumber: 'W912CN-26-Q-0043',
    placeOfPerformance: { city: 'Osan', state: 'Gyeonggi-do', country: 'South Korea' },
    isUsfk: true,
    keywords: ['construction', 'Osan', 'vehicle maintenance', 'Air Force'],
  },
  {
    id: '3',
    noticeId: 'FA5209-26-R-0008',
    title: 'IT Infrastructure Modernization - USFK Command Network',
    type: 'Presolicitation',
    status: 'presolicitation',
    postedDate: '2026-03-20',
    responseDeadline: '2026-03-30',
    agency: 'DEPT OF DEFENSE',
    office: 'PACIFIC AIR FORCES',
    location: 'Seoul, South Korea',
    naicsCode: '541512',
    naicsDescription: 'Computer Systems Design Services',
    estimatedValue: 8500000,
    description: 'Pre-solicitation notice for IT infrastructure modernization services for USFK Command Network. This includes network upgrades, cybersecurity enhancements, and cloud migration services.',
    contactName: 'Mark Thompson',
    contactEmail: 'm.thompson@us.af.mil',
    solicitationNumber: 'FA5209-26-R-0008-PRE',
    placeOfPerformance: { city: 'Seoul', state: 'Seoul', country: 'South Korea' },
    isUsfk: true,
    keywords: ['IT', 'network', 'cybersecurity', 'USFK'],
  },
  {
    id: '4',
    noticeId: 'W912JB-26-B-0021',
    title: 'Food Service Operations - Multiple USFK Installations',
    type: 'Solicitation',
    status: 'active',
    postedDate: '2026-03-10',
    responseDeadline: '2026-03-28',
    agency: 'DEPT OF DEFENSE',
    office: 'INSTALLATION MANAGEMENT COMMAND',
    location: 'Korea',
    naicsCode: '722310',
    naicsDescription: 'Food Service Contractors',
    setAside: 'Small Business',
    estimatedValue: 32000000,
    description: 'Comprehensive food service operations at multiple USFK installations including Camp Humphreys, Camp Casey, and Camp Red Cloud. Services include meal preparation, dining facility management, and catering.',
    contactName: 'Lisa Chen',
    contactEmail: 'l.chen@imcom.army.mil',
    solicitationNumber: 'W912JB-26-B-0021',
    placeOfPerformance: { city: 'Various', state: 'Nationwide', country: 'South Korea' },
    isUsfk: true,
    keywords: ['food service', 'dining', 'USFK', 'Camp Humphreys', 'Camp Casey'],
    saved: true,
  },
  {
    id: '5',
    noticeId: 'SPM3S1-26-D-Z211',
    title: 'Petroleum Products Supply - USFK Aviation Fuel',
    type: 'Award Notice',
    status: 'awarded',
    postedDate: '2026-02-15',
    responseDeadline: '2026-03-01',
    agency: 'DEPT OF DEFENSE',
    office: 'DLA ENERGY',
    location: 'Korea',
    naicsCode: '424710',
    naicsDescription: 'Petroleum and Petroleum Products Merchant Wholesalers',
    estimatedValue: 78000000,
    awardAmount: 75500000,
    awardee: 'SK Energy Co., Ltd.',
    awardDate: '2026-03-12',
    description: 'Supply of aviation fuel (JP-8) and other petroleum products for USFK aircraft operations across multiple installations in South Korea.',
    solicitationNumber: 'SPM3S1-26-D-Z211',
    placeOfPerformance: { city: 'Various', state: 'Nationwide', country: 'South Korea' },
    isUsfk: true,
    keywords: ['fuel', 'aviation', 'petroleum', 'USFK'],
  },
  {
    id: '6',
    noticeId: 'W912JB-26-R-0015',
    title: 'Security Guard Services - USFK Installations',
    type: 'Solicitation',
    status: 'active',
    postedDate: '2026-03-19',
    responseDeadline: '2026-04-20',
    agency: 'DEPT OF DEFENSE',
    office: 'INSTALLATION MANAGEMENT COMMAND',
    location: 'South Korea',
    naicsCode: '561612',
    naicsDescription: 'Security Guards and Patrol Services',
    estimatedValue: 28000000,
    description: 'Unarmed security guard services at various USFK installations throughout South Korea. Requires background checks, English language proficiency, and security clearances.',
    contactName: 'Robert Kim',
    contactEmail: 'r.kim@imcom.army.mil',
    contactPhone: '(010) 1234-5678',
    solicitationNumber: 'W912JB-26-R-0015',
    placeOfPerformance: { city: 'Various', state: 'Nationwide', country: 'South Korea' },
    isUsfk: true,
    keywords: ['security', 'guard', 'USFK', 'protection'],
  },
  {
    id: '7',
    noticeId: 'W912CN-26-R-0033',
    title: 'Environmental Remediation Services - Former Camp Mercer',
    type: 'Sources Sought',
    status: 'presolicitation',
    postedDate: '2026-03-21',
    responseDeadline: '2026-04-04',
    agency: 'DEPT OF DEFENSE',
    office: 'US ARMY CORPS OF ENGINEERS',
    location: 'Incheon, South Korea',
    naicsCode: '562910',
    naicsDescription: 'Remediation Services',
    estimatedValue: 5200000,
    description: 'Sources sought for environmental remediation services at the former Camp Mercer site. Work includes soil and groundwater contamination assessment and remediation.',
    contactName: 'Emily Park',
    contactEmail: 'e.park@usace.army.mil',
    solicitationNumber: 'W912CN-26-R-0033-SS',
    placeOfPerformance: { city: 'Incheon', state: 'Incheon', country: 'South Korea' },
    isUsfk: true,
    keywords: ['environmental', 'remediation', 'cleanup', 'contamination'],
  },
  {
    id: '8',
    noticeId: 'FA5209-26-R-0019',
    title: 'Translation and Interpretation Services - USFK/ROK Joint Command',
    type: 'Solicitation',
    status: 'active',
    postedDate: '2026-03-14',
    responseDeadline: '2026-04-10',
    agency: 'DEPT OF DEFENSE',
    office: 'UNITED STATES FORCES KOREA',
    location: 'Seoul, South Korea',
    naicsCode: '541930',
    naicsDescription: 'Translation and Interpretation Services',
    estimatedValue: 3800000,
    description: 'Professional Korean-English translation and interpretation services for USFK and ROK-US Combined Forces Command operations, including document translation, simultaneous interpretation, and written communications.',
    contactName: 'David Lee',
    contactEmail: 'd.lee@usfk.mil',
    solicitationNumber: 'FA5209-26-R-0019',
    placeOfPerformance: { city: 'Seoul', state: 'Seoul', country: 'South Korea' },
    isUsfk: true,
    keywords: ['translation', 'interpretation', 'Korean', 'English', 'USFK'],
    saved: true,
  },
  {
    id: '9',
    noticeId: 'W912CN-26-C-0041',
    title: 'Military Housing Renovation - Camp Walker',
    type: 'Award Notice',
    status: 'awarded',
    postedDate: '2026-02-20',
    responseDeadline: '2026-03-10',
    agency: 'DEPT OF DEFENSE',
    office: 'US ARMY CORPS OF ENGINEERS',
    location: 'Daegu, South Korea',
    naicsCode: '236118',
    naicsDescription: 'Residential Remodelers',
    awardAmount: 15800000,
    awardee: 'Samsung C&T Corporation',
    awardDate: '2026-03-18',
    description: 'Renovation of family housing units at Camp Walker, Daegu. Work includes interior renovation, HVAC upgrades, and accessibility improvements.',
    solicitationNumber: 'W912CN-26-C-0041',
    placeOfPerformance: { city: 'Daegu', state: 'Daegu', country: 'South Korea' },
    isUsfk: true,
    keywords: ['housing', 'renovation', 'construction', 'Camp Walker'],
  },
  {
    id: '10',
    noticeId: 'SPE7MX-26-Q-0088',
    title: 'Medical Supplies and Equipment - US Army Garrison Humphreys',
    type: 'Combined Synopsis/Solicitation',
    status: 'active',
    postedDate: '2026-03-22',
    responseDeadline: '2026-03-29',
    agency: 'DEPT OF DEFENSE',
    office: 'DLA TROOP SUPPORT',
    location: 'Camp Humphreys, South Korea',
    naicsCode: '339112',
    naicsDescription: 'Surgical and Medical Instrument Manufacturing',
    setAside: 'Total Small Business Set-Aside',
    estimatedValue: 1200000,
    description: 'Supply of medical supplies, equipment, and consumables for Brian D. Allgood Army Community Hospital at Camp Humphreys.',
    contactName: 'Patricia Brown',
    contactEmail: 'p.brown@dla.mil',
    solicitationNumber: 'SPE7MX-26-Q-0088',
    placeOfPerformance: { city: 'Pyeongtaek', state: 'Gyeonggi-do', country: 'South Korea' },
    isUsfk: true,
    keywords: ['medical', 'supplies', 'hospital', 'Camp Humphreys'],
  },
  {
    id: '11',
    noticeId: 'W91QVN-26-R-0004',
    title: 'Logistics and Transportation Support - 8th Army',
    type: 'Modification/Amendment',
    status: 'modified',
    postedDate: '2026-03-16',
    responseDeadline: '2026-04-05',
    agency: 'DEPT OF DEFENSE',
    office: '8TH UNITED STATES ARMY',
    location: 'South Korea',
    naicsCode: '488999',
    naicsDescription: 'All Other Support Activities for Transportation',
    estimatedValue: 22000000,
    description: 'Amendment 0002: Updated statement of work for logistics and transportation support services for 8th Army units across Korea. Includes vehicle dispatch, container management, and port operations support.',
    contactName: 'Thomas Wilson',
    contactEmail: 't.wilson@8tharmy.mil',
    solicitationNumber: 'W91QVN-26-R-0004',
    placeOfPerformance: { city: 'Various', state: 'Nationwide', country: 'South Korea' },
    isUsfk: true,
    keywords: ['logistics', 'transportation', '8th Army', 'USFK'],
  },
  {
    id: '12',
    noticeId: 'FA5209-26-R-0022',
    title: 'HVAC Maintenance and Repair - Kunsan Air Base',
    type: 'Solicitation',
    status: 'active',
    postedDate: '2026-03-17',
    responseDeadline: '2026-04-08',
    agency: 'DEPT OF DEFENSE',
    office: 'PACIFIC AIR FORCES',
    location: 'Kunsan, South Korea',
    naicsCode: '238220',
    naicsDescription: 'Plumbing, Heating, and Air-Conditioning Contractors',
    setAside: 'Small Business',
    estimatedValue: 4500000,
    description: 'Maintenance, repair, and operations of HVAC systems at Wolf Pack, Kunsan Air Base. Includes preventive maintenance, emergency repairs, and energy efficiency improvements.',
    contactName: 'Jennifer Adams',
    contactEmail: 'j.adams@kunsan.af.mil',
    solicitationNumber: 'FA5209-26-R-0022',
    placeOfPerformance: { city: 'Kunsan', state: 'North Jeolla', country: 'South Korea' },
    isUsfk: true,
    keywords: ['HVAC', 'maintenance', 'Kunsan', 'Air Force', 'repair'],
  },
];

export const mockAwardData: AwardData[] = [
  { year: 2025, month: '2025-01', agency: 'DLA TROOP SUPPORT', awardee: 'CJ CheilJedang', amount: 45000000, naicsCode: '722310', naicsDescription: 'Food Service Contractors', title: 'Food Service Operations FY2025' },
  { year: 2025, month: '2025-02', agency: 'USACE', awardee: 'Samsung C&T', amount: 32000000, naicsCode: '236220', naicsDescription: 'Commercial Building Construction', title: 'Facility Construction Phase 1' },
  { year: 2025, month: '2025-03', agency: 'DLA ENERGY', awardee: 'SK Energy', amount: 68000000, naicsCode: '424710', naicsDescription: 'Petroleum Products', title: 'JP-8 Aviation Fuel Supply' },
  { year: 2025, month: '2025-04', agency: 'IMCOM', awardee: 'S1 Corporation', amount: 18500000, naicsCode: '561612', naicsDescription: 'Security Guard Services', title: 'Installation Security Services' },
  { year: 2025, month: '2025-05', agency: 'USACE', awardee: 'Hyundai E&C', amount: 41000000, naicsCode: '236220', naicsDescription: 'Commercial Building Construction', title: 'Barracks Renovation Program' },
  { year: 2025, month: '2025-06', agency: 'DLA TROOP SUPPORT', awardee: 'Daesang Corp', amount: 12000000, naicsCode: '722310', naicsDescription: 'Food Service Contractors', title: 'Supplemental Food Services' },
  { year: 2025, month: '2025-07', agency: 'PACAF', awardee: 'LG CNS', amount: 9500000, naicsCode: '541512', naicsDescription: 'IT Systems Design', title: 'Network Infrastructure Upgrade' },
  { year: 2025, month: '2025-08', agency: 'IMCOM', awardee: 'POSCO E&C', amount: 27000000, naicsCode: '236118', naicsDescription: 'Residential Renovation', title: 'Family Housing Renovation' },
  { year: 2025, month: '2025-09', agency: 'DLA ENERGY', awardee: 'GS Caltex', amount: 71000000, naicsCode: '424710', naicsDescription: 'Petroleum Products', title: 'Ground Fuel Supply Contract' },
  { year: 2025, month: '2025-10', agency: 'USACE', awardee: 'Samsung C&T', amount: 38000000, naicsCode: '236220', naicsDescription: 'Commercial Building Construction', title: 'Training Facility Construction' },
  { year: 2025, month: '2025-11', agency: 'DLA TROOP SUPPORT', awardee: 'CJ CheilJedang', amount: 16000000, naicsCode: '722310', naicsDescription: 'Food Service Contractors', title: 'Holiday Food Services' },
  { year: 2025, month: '2025-12', agency: 'IMCOM', awardee: 'S1 Corporation', amount: 22000000, naicsCode: '561612', naicsDescription: 'Security Guard Services', title: 'Expanded Security Coverage' },
];

export const mockCompetitors: CompetitorData[] = [
  { name: 'Samsung C&T Corporation', totalAwards: 8, totalValue: 185000000, avgValue: 23125000, naicsCodes: ['236220', '236118', '237310'], recentWin: '2026-03-18' },
  { name: 'SK Energy Co., Ltd.', totalAwards: 5, totalValue: 312000000, avgValue: 62400000, naicsCodes: ['424710', '424720'], recentWin: '2026-03-12' },
  { name: 'Hyundai E&C', totalAwards: 6, totalValue: 142000000, avgValue: 23666667, naicsCodes: ['236220', '236118'], recentWin: '2025-11-20' },
  { name: 'CJ CheilJedang', totalAwards: 4, totalValue: 89000000, avgValue: 22250000, naicsCodes: ['722310'], recentWin: '2025-11-15' },
  { name: 'S1 Corporation', totalAwards: 7, totalValue: 95000000, avgValue: 13571429, naicsCodes: ['561612', '561621'], recentWin: '2025-12-01' },
  { name: 'LG CNS', totalAwards: 3, totalValue: 28500000, avgValue: 9500000, naicsCodes: ['541512', '541511'], recentWin: '2025-07-15' },
  { name: 'GS Caltex', totalAwards: 4, totalValue: 245000000, avgValue: 61250000, naicsCodes: ['424710'], recentWin: '2025-09-10' },
  { name: 'POSCO E&C', totalAwards: 3, totalValue: 78000000, avgValue: 26000000, naicsCodes: ['236220', '237310'], recentWin: '2025-08-22' },
];

export const mockUsers: User[] = [
  { id: '1', name: '김민준', email: 'minjun.kim@company.co.kr', role: 'admin', department: '사업개발팀', isActive: true, createdAt: '2025-01-10', lastLogin: '2026-03-24' },
  { id: '2', name: '이서연', email: 'seoyeon.lee@company.co.kr', role: 'manager', department: '입찰관리팀', isActive: true, createdAt: '2025-02-15', lastLogin: '2026-03-23' },
  { id: '3', name: '박지호', email: 'jiho.park@company.co.kr', role: 'manager', department: '입찰관리팀', isActive: true, createdAt: '2025-03-01', lastLogin: '2026-03-22' },
  { id: '4', name: '최유나', email: 'yuna.choi@company.co.kr', role: 'viewer', department: '전략기획팀', isActive: true, createdAt: '2025-06-20', lastLogin: '2026-03-20' },
  { id: '5', name: '정도현', email: 'dohyun.jung@company.co.kr', role: 'viewer', department: '재무팀', isActive: false, createdAt: '2025-08-11', lastLogin: '2026-02-14' },
];

export const mockLogs: SystemLog[] = [
  { id: '1', timestamp: '2026-03-24 09:00:01', level: 'info', message: 'SAM.gov API 데이터 수집 완료', details: '신규 공고 3건, 변경 공고 2건 수집' },
  { id: '2', timestamp: '2026-03-24 09:00:05', level: 'info', message: '알림 발송 완료', details: '이메일 2건, SMS 1건 발송' },
  { id: '3', timestamp: '2026-03-24 06:00:01', level: 'info', message: 'SAM.gov API 데이터 수집 완료', details: '신규 공고 1건 수집' },
  { id: '4', timestamp: '2026-03-23 21:00:01', level: 'warning', message: 'API 응답 지연 감지', details: 'SAM.gov API 응답 시간 3.2초 (임계값: 3초)' },
  { id: '5', timestamp: '2026-03-23 18:00:01', level: 'info', message: 'SAM.gov API 데이터 수집 완료', details: '신규 공고 5건, 변경 공고 1건 수집' },
  { id: '6', timestamp: '2026-03-23 15:00:01', level: 'error', message: 'SAM.gov API 연결 오류', details: 'Connection timeout after 30s. Retried 3 times.' },
  { id: '7', timestamp: '2026-03-23 12:00:01', level: 'info', message: 'SAM.gov API 데이터 수집 완료', details: '신규 공고 2건 수집' },
  { id: '8', timestamp: '2026-03-23 09:00:01', level: 'info', message: '사용자 로그인', details: '이서연 (seoyeon.lee@company.co.kr)' },
];

export const mockStats: DashboardStats = {
  totalBids: 1247,
  newToday: 23,
  closingSoon: 8,
  awards: 156,
  totalAwardValue: 1850000000,
  matchedFilters: 47,
};
